### ISSUE TITLE
Error occured after running npm run dev

### ISSUE THREAD

**Issue by seyo-IV** [openai/openai-quickstart-node#34]
### Describe the bug

`root@chat:/opt/chatGPT/openai-quickstart-node# npm run dev 
> openai-quickstart-node@0.1.0 dev /opt/chatGPT/openai-quickstart-node                                                > next dev                                                 
/opt/chatGPT/openai-quickstart-node/node_modules/next/dist/cli/next-dev.js:309
            showAll: args["--show-all"] ?? false,                                                   ^
                                                           SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)                                                              at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)         at Object.dev (/opt/chatGPT/openai-quickstart-node/node_modules/next/dist/lib/commands.js:10:30)
    at Object.<anonymous> (/opt/chatGPT/openai-quickstart-node/node_modules/next/dist/bin/next:141:28)                    at Module._compile (internal/modules/cjs/loader.js:778:30)                                                        npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openai-quickstart-node@0.1.0 dev: `next dev`      npm ERR! Exit status 1                                     npm ERR!                                                   npm ERR! Failed at the openai-quickstart-node@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                    
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-14T19_43_30_894Z-debug.log`

### To Reproduce

Enter command: npm run dev

See error above.

### OS

Ubuntu 22.04

### Node version

v10.19.0

**Comment by desmondtch** [comment]
I am facing the same error as well, and looking forward to a fix.

**Comment by schnerd** [comment]
This is a next.js based application, which requires a minimum node.js version of 14.6.0.

I'd recommend installing a newer version of node (possibly using something like [nvm](https://github.com/nvm-sh/nvm))

We'll try to better document the requirements in this project.

**Comment by mojo8787** [comment]
guys please help 
now i am trying to put the instruction of openai but faild . 

how can i add the api key ? or where

**Comment by JoelAzevedo** [comment]
Having the same issue two. Any ETA for the fix? Thanks.

**Comment by schnerd** [comment]
The solution for this issue is to upgrade the version of node you are using. This project requires node >= 14.6.0.
